"""role user update

Revision ID: 5af13be808ca
Revises: 4dc0923c244a
Create Date: 2026-08-17 16:25:25.257023-03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores da migração, usados pelo Alembic.
revision: str = '5af13be808ca'
down_revision: Union[str, None] = '4dc0923c244a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###