"""remove role

Revision ID: a7ba39c5609c
Revises: 5af13be808ca
Create Date: 2026-08-19 15:42:14.908183-03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# identificadores da migração, usados pelo Alembic.
revision: str = 'a7ba39c5609c'
down_revision: Union[str, None] = '5af13be808ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('ADMIN', 'MANAGER', 'RECIPIENT', name='role'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###