"""baseline

Revision ID: 26d06ef9ead7
Revises: 
Create Date: 2026-08-15 20:34:16.678525-03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores da migração, usados pelo Alembic.
revision: str = '26d06ef9ead7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###