"""role user

Revision ID: 4dc0923c244a
Revises: 26d06ef9ead7
Create Date: 2026-08-17 16:12:14.904785-03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores da migração, usados pelo Alembic.
revision: str = '4dc0923c244a'
down_revision: Union[str, None] = '26d06ef9ead7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    role_enum = sa.Enum(
        'ADMIN',
        'MANAGER',
        'RECIPIENT',
        name='role'
    )

    role_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'RECIPIENT', name='role'), nullable=True))
    # ### end Alembic commands ###

    op.execute(
        "UPDATE users SET role = 'RECIPIENT' WHERE role IS NULL"
    )

    op.alter_column(
        'users',
        'role',
        existing_type=role_enum,
        nullable=False
    )


def downgrade() -> None:
    role_enum = sa.Enum(
        'ADMIN',
        'MANAGER',
        'RECIPIENT',
        name='role'
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
    role_enum.drop(op.get_bind(), checkfirst=True)